site:
  title: PalmSens for Developers
  start_page: start::index.adoc
  url: https://sdk.palmsens.com
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs/start
    - url: .
      branches: HEAD
      tags: [python-1.5.0, python-1.4.0, python-1.3.3, python-1.2.2, python-1.1.1]
      version:
        main: dev
        python-(?<version>+({0..9}).+({0..9})).*: $<version>
      start_path: python/docs
    - url: .
      branches: HEAD
      tags: ['matlab-1.0.1']
      start_path: matlab/docs
      versions:
        main: dev
        matlab-(?<version>+({0..9}).+({0..9})).*: $<version>
    - url: .
      branches: HEAD
      tags: ['labview-1.0.0']
      start_path: labview/docs
      versions:
        main: dev
        labview-(?<version>+({0..9}).+({0..9})).*: $<version>
    - url: .
      branches: HEAD
      tags: ['maui-1.2.3']
      start_path: maui/docs
      versions:
        main: dev
        maui-(?<version>+({0..9}).+({0..9})).*: $<version>
urls:
  latest_version_segment: latest
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui
antora:
  extensions:
    - require: '@antora/collector-extension'
      enabled: true
    - require: '@antora/lunr-extension'
      enabled: true
