site:
  title: PalmSens for Developers
  start_page: start::index.adoc
  url: https://sdk.palmsens.com
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs/start
    - url: .
      branches: HEAD
      start_path: python/docs
    - url: .
      branches: HEAD
      start_path: matlab/docs
    - url: .
      branches: HEAD
      start_path: labview/docs
    - url: .
      branches: HEAD
      start_path: maui/docs
    - url: .
      branches: HEAD
      start_path: winforms/docs
    - url: .
      branches: HEAD
      start_path: wpf/docs
urls:
  latest_version_segment: latest
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui
antora:
  extensions:
    - require: '@antora/collector-extension'
      enabled: true
    - require: '@antora/lunr-extension'
      enabled: true
