[tool.bumpversion]
current_version = "1.0.0"

[[tool.bumpversion.files]]
filename = "docs/antora.yml"
search = "version: '{current_version}'"
replace = "version: '{new_version}'"

[[tool.bumpversion.files]]
filename = "/docs/modules/ROOT/nav.adoc"
search = "winforms-{current_version}"
replace = "winforms-{new_version}"
