name: Publish Maui

on:
  push:
    tags:
      - 'maui-*'
  workflow_dispatch:

jobs:
  build:
    name: Add maui zip to release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install bump-my-version
      run: |
        python -m pip install bump-my-version

    - name: Set configuration
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Get tag (strip maui prefix)
      run: |
        echo "TAG=${GITHUB_REF_NAME#maui-}" >> $GITHUB_ENV

    - name: Bump version to new tag
      run: |
        cd maui
        bump-my-version bump --new-version ${{ env.TAG }} patch
        git commit -am "Bump version to: ${{ env.TAG }}"

    - name: Push back changes to main and tag
      run: |
        git tag --force $GITHUB_REF_NAME HEAD
        git push --force --tags
        git switch -C main
        git push --set-upstream -f origin main

    - name: Zip maui directory
      run: |
        cd maui
        zip -r ../${{ github.ref_name }}.zip *
        cd ..

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.ref_name }}.zip
        path: ${{ github.ref_name }}.zip

    # https://github.com/softprops/action-gh-release
    - name: Add zip to tagged release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/maui-')
      with:
        files: ${{ github.ref_name }}.zip
